version: '3.8'

services:
  # =========================================
  # FastAPI 後端程式
  # =========================================
  backend:
    build: .  # 這裡會讀取當前目錄的 Dockerfile 來打包
    container_name: audiophile_backend
    restart: always
    ports:
      - "8000:8000"  
    depends_on:      
      - db
      - redis
      - mongo
    
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      
      - REDIS_URL=redis://redis:6379/0
      
      - MONGO_HOST=mongo
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
    
    volumes:
      - ./src:/app/src

  # =========================================
  # Infra
  # =========================================
  db:
    image: postgres:15-alpine
    container_name: audiophile_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: audiophile_redis
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: audiophile_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./docker_data/mongo:/data/db